version: "3.7"

services:
  db:
    image: postgres:13
    ports:
      - "172.17.0.1:5432:5432"
    environment:
      - POSTGRES_PASSWORD=listmonk
      - POSTGRES_USER=listmonk
      - POSTGRES_DB=listmonk
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U listmonk"]
      interval: 10s
      timeout: 5s
      retries: 6
    container_name: listmonk_db
    volumes:
      - ./listmonk-data:/var/lib/postgresql/data

  app:
    restart: unless-stopped
    image: listmonk/listmonk:latest
    command: [sh, -c, "yes | ./listmonk --install --config config.toml && ./listmonk && ./listmonk --upgrade --yes --config config.toml"]
    ports:
      - "172.17.0.1:9090:9000"
    environment:
      - TZ=Etc/UTC
    container_name: listmonk_app
    depends_on:
      - db
    volumes:
      - ./config.toml:/listmonk/config.toml
